name: ${project.name}
version: ${project.version}-${releaseStatus}
description: ''
author: Snoop1CattZ69
authors: [Snoop1CattZ69, ASL std.]
website: http://vk.com/aslrb

api-version: 1.13

main: org.aslstd.slr.core.SLR
depend: [ejCore]
softdepend: [Vault, Essentials]

commands:
  aseller: